node_js:
  - 10
  - 11
  - 12
  - 14
  - 15
language: node_js
script: "npm run-script test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

deploy:
  provider: npm
  email: "sageptr@gmail.com"
  api_key:
    secure: "Qaes1Vy6WpbIEOPr3TzrB3HtuVYWoioUx3Vsa+qtEE4oAGRvKrnECoh9X1sFpzG0FLK1ugmqvkLfov9wj9Yj1MAhR/nq665n8ANFHSmC7bXv9Cmnu4/D56BO2D0vk50vjgX5x+RUGHX0KBQ8mbLFQzmKu3w0h1J/s+mOuTearEuEgQ+9gMDLlD7eHFy77ODMT/lmLYtBaXo07+qKsHuMgSyv1u+qLno7FAd+Le7i5bSdmPwyfnk2eOB1gAuMDMkc1vrL5KFHUMumyoUtZIEDJNXXQBIIxo7ozV1sKn6x42YAHRf92qJqBnVYfG/LqGQo+ygtGVRmg6O7wC4sBu8nyuw0Ex+nvstXDRLUpddRcUoIQqUnJV0wd9o8lOVNqdr1OgFmiwWidV364n4hEfOK53agi8Bezf+S++hOt6K7kQ2meVC1B+S6ZcJ1FQLmX+Q/06k3DR4V5UrKlRQdVaGEoZceq8QxS+dbjTITWEL30wP6ppKGlYCrpokVWG8YvxnKRey+Fxv/FAXNNXfaPp+CUjO9yTSgfZXZUrfsxAJPcsljELJWEQKB/ezTRBjSskMU/BX1cdc9/Q0YfZ8DY5jHpInELeff4CWTslyAsjdNFlUxfFcbzVOzJb6sKAZHD5/qvEhVD62YH3A9F1I+izk8jXWlgPixTK/539w8EtlfgH4="
  on:
    tags: true
