node_js:
  - 10
  - 11
  - 12
  - 14
  - 15
language: node_js
script: "npm run-script test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

deploy:
  provider: npm
  email: "sageptr@gmail.com"
  api_key:
    secure: "h2B7dVZqp+aABiqH/2M+r3BImXJgZPszOLNjmknrwtr3KvGDZ1ear+AY+5w91k7reGhb1DBVLo6NO4DPY1/onc/3iJ0OX3NnaDszxIu9BX2UaIwIMnZI4V5BMOgi9wDGfJvNPbuGqgsCKlqTpfHu1ZApuusiYizU7xNhUrmjD+2YquPhiFb9UcQxHVb+Vf7KWE6lJXGZwM3BOLO9dM7ncqFfn0c0GN66CZH+ep1H3ieTiKZQDIXms5tjMCmXJZt46L9/+PPA1PrSCJsKbxyzkhkeIWgF1ly0/Y7qaROGaR1yeE0EpXEmpSwuimVO7rx4bfBNsty7si9waSE75fZLq5B13eJgHZGXi1Ze6M1/JrKXM+F8ldnIcGDuwADrIu2cD7/gL1IZWaSHf4i9XC4BtFp6KVcIM//Kubqw5mE5aYsVqFFV/RUP1Xpm0GxkVrvbO5Rm8dD6H9UDdyVPWcylnbI4LJoERo3UplZ4WYIqKFBxs+orwhQMXwaDVOiaQrCWAH4hbUNJG+aBJ9YxacMyjcZECdrZS5SC/Gmq0RcqDaqLJPPqg3+vEBbmHWLQP6y6tcWREt2+D2tu5Fj+QBkRdUldIc41GyGMpIKFPyHqdRw9whLQZQXnv+4OXZiGCSTIj1E9B5EcU9CD4Ix8pAJWMS5044X1GO/bWpazFqzzXCA="
  on:
    tags: true
